repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.6.0'
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/myint/autoflake
    rev: 'v2.3.1'
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --remove-duplicate-keys
          - --ignore-init-module-imports
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.9'
    hooks:
      - id: bandit
        args:
          - --ini
          - setup.cfg
        exclude: tests/
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: '24.4.2'
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
  - repo: https://github.com/asottile/blacken-docs
    rev: '1.18.0'
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==23.7.0
  - repo: https://github.com/PyCQA/flake8
    rev: '7.1.0'
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-blind-except
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-debugger
          - flake8-docstrings
          - flake8-isort
          - flake8-polyfill
          - flake8-pytest
          - flake8-quotes
          - flake8-typing-imports
          - yesqa
  - repo: https://github.com/PyCQA/isort
    rev: '5.13.2'
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.10.1'
    hooks:
      - id: mypy
        args:
          - --show-error-codes
        additional_dependencies:
          - types-requests
          - types-beautifulsoup4
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: 'v1.10.0'
    hooks:
      - id: python-check-mock-methods
      - id: rst-backticks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.6.0'
    hooks:
      - id: debug-statements
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        language: system
        exclude: tests/
        entry: pylint
        types:
          - python
  - repo: https://github.com/pappasam/toml-sort
    rev: 'v0.23.1'
    hooks:
      - id: toml-sort-fix
default_language_version:
  python: python3.12
